name: LocalTunnel Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install LocalTunnel
      run: sudo npm install -g localtunnel

    - name: Start LocalTunnel
      run: |
        lt --port 3389 --subdomain mycustomsubdomain > lt.log &
        sleep 10  # Wait for LocalTunnel to start
        cat lt.log | grep "https://" || echo "LocalTunnel URL not found"
        # Save the URL for later use
        URL=$(cat lt.log | grep "https://" | awk '{print $2}')
        echo "URL=$URL" >> $GITHUB_ENV

    - name: Retrieve Tunnel Password
      run: |
        # Fetch the tunnel password
        PASSWORD=$(curl -s https://loca.lt/mytunnelpassword)
        echo "Tunnel password is: $PASSWORD"
        echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV

    - name: Output LocalTunnel URL and Password
      run: |
        echo "LocalTunnel URL: ${{ env.URL }}"
        echo "Tunnel Password: ${{ env.PASSWORD }}"

    - name: Cleanup
      run: |
        # Optionally stop the LocalTunnel process if needed
        pkill -f lt


    - name: Cleanup
      run: |
        # Optionally stop the LocalTunnel process if needed
        pkill -f lt
